baseURL = "https://yonshisoru.github.io/blog/"
title = "JustABlog"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = true
buildExpired = true
googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "JustABlog"
author = "Yonshisoru"
DateFormat = "Mon, 02 Jan 2006 15:04:05 MST"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false


  [params.assets]
  favicon = "/blog/blog-icon.ico"
  favicon16x16 = "/blog/blog-icon.ico"
  favicon32x32 = "/blog/blog-icon.ico"


  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/yonshisoru_"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Yonshisoru"


  [params.cover]
    image = "/blog/duck.jpg"
    alt = "no more duck"
    caption = "Just a duck"
    relative = false


  [params.editPost]
  URL = "https://github.com/Yonshisoru/blog/blob/main/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 3


[[menu.main]]
identifier = "archives"
name = "archives"
url = "/archives/"
weight = 1
